service: M365-Renew-V2
plugins:
  - serverless-localstack
provider:
  name: aws
  runtime: nodejs24.x
  architecture: x86_64
  region: us-east-2
  versionFunctions: false
  stackName: '${self:service}'
  role:
    'Fn::GetAtt':
      - ExecutionRole
      - Arn
  logRetentionInDays: 30
  environment:
    USERS_TABLE: '${self:service}-Users'
    PROCESSING_LOG_TABLE: '${self:service}-Processing-Log'
    AES_ENCRYPTION_KEY: '${env:AES_ENCRYPTION_KEY}'
    NOTIFICATION_PROVIDER: '${env:NOTIFICATION_PROVIDER, "sns"}'
    MAIL_MEOW_BASE_URL: '${env:MAIL_MEOW_BASE_URL, ""}'
    MAIL_MEOW_API_KEY: '${env:MAIL_MEOW_API_KEY, ""}'
    SNS_TOPIC_ARN: '${file(./serverless/notifications/${env:NOTIFICATION_PROVIDER, "sns"}.yml):environment.SNS_TOPIC_ARN}'
    TOTP_SERVER_BASE_URL: '${env:TOTP_SERVER_BASE_URL}'
    AWS_ENDPOINT_URL: '${env:M365_AWS_ENDPOINT_URL, env:AWS_ENDPOINT_URL, ""}'
functions:
  api:
    handler: src/handler.api
    name: '${self:service}-API'
    timeout: 10
    memorySize: 512
    reservedConcurrency: 0
    url:
      cors: true
  scheduler:
    handler: src/handler.scheduler
    name: '${self:service}-Scheduler'
    timeout: 120
    memorySize: 2560
    events:
      - schedule: rate(280 minutes)
resources:
  - ${file(./serverless/resources/base.yml)}
  - ${file(./serverless/notifications/${env:NOTIFICATION_PROVIDER, "sns"}.yml):resources}
useDotenv: true
build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    external:
      - '@sparticuz/chromium'
custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
